### ISSUE TITLE
Repeat login require before Build

### ISSUE THREAD

**Issue by xpsuper** [chandlerhuff/iJenkins#1]
Repeat login require before Build, can't start Building

**Comment by chandlerhuff** [comment]
@xpsuper I think this happens if the Jenkins server is not accessible so try opening it in a web browser or check the username and password you have set. Also if you are using folders only top level folders work so that might be the issue. But you might get more help on the iJenkins repo and not this fork.

**Comment by chandlerhuff** [comment]
@xpsuper I just setup a new server and was having this issue it was because I had CSRF Protection enabled I have added support for CSRF Protection in 246a1abcbae9607b7ba650c9fa9bf41aa8a24157
